name: Test and Publish Dev

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Java Env
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: 'maven'

    - name: Check Format
      uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--replace"
        skip-commit: true

    - name: Show Diff
      run: git --no-pager diff --exit-code

    - name: Test Project
      run: mvn test

    - name: Package Project
      run: mvn package -DskipTests

    - name: Prepare Publish Project
      run: mkdir publish && cp target/*.jar publish

    - name: Publish Project
      uses: actions/upload-artifact@v4
      with:
        name: oop2-ze
        path: publish
